# Generated by Django 2.2.5 on 2019-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemeuser',
            name='profile_state',
            field=models.IntegerField(default=0),
        ),
    ]
