# Generated by Django 2.2.5 on 2019-10-17 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.IntegerField(default=0)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.TextField(default=0)),
                ('photo', models.ImageField(blank=True, default='profiles/default_user.png', upload_to='profiles')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='join date')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
